[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
up_only = "9taCctXUoxDPeqK4eLX3U7d4K953kM6QLJucPcoZUeRZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/araba/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
